title: Natalia Soares
email: hello@natisoares.com
description: UI/UX Designer passionate about responsive, accessible websites and illustrations.
baseurl: "/"
url: "http://natisoares.com"

theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/stylesheets
  style: compressed

include:
  - _redirects
  - netlify.toml

exclude:
  - assets/sass
  - README.MD
  - Gemfile
  - Gemfile.lock
  - vendor